### ISSUE TITLE
LICENSE for waybar-mpris

### ISSUE THREAD

**Issue by solacelost** [hrfee/mpris2client#2]
I'd like to package waybar-mpris, hopefully getting it on COPR, for Fedora. Fedora has a strict policy about FOSS, so I'd need to ensure that I'm following the [packaging guidelines](https://docs.fedoraproject.org/en-US/packaging-guidelines/Golang/#_spec_preamble_goipath_forgeurl_and_gometa) and explicitly declaring the license.

[waybar-mpris](https://git.hrfee.pw/hrfee/waybar-mpris) is currently published without a license, so all rights are currently reserved for you and it's not FOSS by definition as you've not licensed the community to use, modify, or redistribute your work.

I'd appreciate you dropping a LICENSE on there for me :)

**Comment by hrfee** [comment]
Thanks for offering to package it! I'll put the MIT License on it now.

**Comment by hrfee** [comment]
Also, drop a link here or on my email once you've finished and I'll add it to the README,

**Comment by solacelost** [comment]
It's not going to make it into the official repos, or even COPR (the Fedora equivalent of a PPA or the AUR), just yet. They don't like accepting packages without tags, but I've successfully built and published it on my own repo for now and want to do some testing before I push for it on the COPR. Would be helpful for you to cut release tags before then!

In the meantime this works:
https://git.jharmison.com/jharmison/waybar-mpris-rpm/releases

Also, see:
https://git.jharmison.com/containers/repo-jharmison-com
https://repo.jharmison.com
(I don't envision people will be jumping up and down to install my repo for now, though :))

Happy to have found another Gitea and Drone user, though ;)

**Comment by hrfee** [comment]
Ok, will do.
